// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

// NOTE: Lovable no soporta leer VITE_* en runtime; usa valores directos del proyecto.
// (La anon key es pública; no uses service role key en el frontend.)
const SUPABASE_URL = "https://gcjlruhcnrmfdiaisxri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjamxydWhjbnJtZmRpYWlzeHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNDA3NjAsImV4cCI6MjA4MjYxNjc2MH0.A3Xf9qHBhfxjSE5TSiGe5uBh12SNeUhHOHoABwFTgFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Usamos cliente sin tipado generado porque `types.ts` está vacío en este proyecto.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
